### ISSUE TITLE
Detecting when entry status changes from scheduled to live

### ISSUE THREAD

**Issue by jamesmacwhite** [putyourlightson/craft-element-status-events#3]
@putyourlightson Thanks for this and your write up here: https://craftcodingchallenge.com/challenge-6-the-chicken-or-the-egg. I'm looking to use your module to hook into a specific entry section and check if an entry goes from "Pending" to "Live". The reason for this is because I have a template part that pulls in entries from this section which is cached. Craft itself won't clear the cache when a pending entry status changes to live, so I was wanting to use your module to hook into the event and force the template caches to be cleared.

Does your module allow for this at all? Can it detect when something scheduled changes to live, given the date is in the future?

**Comment by jamesmacwhite** [comment]
Ah sorry, totally missed the Cron part, running that then triggers my code.

FYI there is a typo for the cron command `php craft element-status-events/scheduled`.

**Comment by putyourlightson** [comment]
Thanks, fixed the typo.

**Comment by jamesmacwhite** [comment]
No problem. Thanks for creating this module, really cool event to hook into!
