### ISSUE TITLE
statusBeforeSave property is always ''

### ISSUE THREAD

**Issue by jamiepittock** [putyourlightson/craft-element-status-events#5]
### Describe the bug
The event's `statusBeforeSave` property always seems to be `''` so the event is always triggered. 

I'm using Craft 3.5.7.

I've done by best to make sure I'm not missing something obvious...apologies if you're about to point something out to me!

Any idea what the problem might be?

**Comment by jamiepittock** [comment]
I realised it's down to the changes made to how drafts and revisions work in 3.2 (?).

Adding the following check in the `rememberPreviousStatus` and `fireEventOnChange` event listeners seems to fix the issue.

    // Prevent on updates of drafts or revisions
    if (ElementHelper::isDraftOrRevision($element)) {
        return;
    }

We might end up going with something custom because our needs are quite specific + we have Product and custom element types to deal with. Let me know if you'd like a PR for this though.

**Comment by bencroker** [comment]
Sorry for not responding sooner, this went under my radar, somehow.

Yes, the 3.x updates changed a lot of things. This package is now outdated, with no immediate plans to update it, unfortunately. But you can absolutely fork it or integrate into your own custom module/plugin.
